# Example: sync OpenClaw user settings into the cluster as `secret/openclaw-user`.
# Must include `OPENCLAW_OWNER_PHONE` if you want allowFrom to be set automatically.
# Copy this file to a new *.yaml and fill in the placeholders.
# Files ending in .example.yaml are ignored by our mise tasks.

apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openclaw-user
  namespace: openclaw
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 300
  instantUpdates: false

  authentication:
    universalAuth:
      secretsScope:
        projectSlug: REPLACE_ME_PROJECT_SLUG
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: infisical-operator-system

  managedKubeSecretReferences:
    - secretName: openclaw-user
      secretNamespace: openclaw
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
